apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: free-bird-api
  description: Retrieve bird info
  namespace: free-bird
spec:
  type: openapi
  lifecycle: production
  owner: mbrouer
  system: demo
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Free Bird API
      license:
        name: MIT
    servers:
      - url: http://freebird/v1
    paths:
      /birds:
        get:
          summary: List all birds
